//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeManage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdgeManage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EdgeManage {
            get {
                object obj = ResourceManager.GetObject("EdgeManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported column type: .
        /// </summary>
        internal static string errBadCol {
            get {
                return ResourceManager.GetString("errBadCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check for updates: .
        /// </summary>
        internal static string errCheckUpdate {
            get {
                return ResourceManager.GetString("errCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is corrupted.
        /// </summary>
        internal static string errCorrupt {
            get {
                return ResourceManager.GetString("errCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file is missing.
        /// </summary>
        internal static string errMissing {
            get {
                return ResourceManager.GetString("errMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update: .
        /// </summary>
        internal static string errUpdate {
            get {
                return ResourceManager.GetString("errUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string msgAttention {
            get {
                return ResourceManager.GetString("msgAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Complete.
        /// </summary>
        internal static string msgBackup {
            get {
                return ResourceManager.GetString("msgBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the backup: .
        /// </summary>
        internal static string msgBackupErr {
            get {
                return ResourceManager.GetString("msgBackupErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string msgCancelled {
            get {
                return ResourceManager.GetString("msgCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will discard any changes and start over with an empty Favorites list
        ///Do you want to continue?.
        /// </summary>
        internal static string msgClear {
            get {
                return ResourceManager.GetString("msgClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the Edge browser and then restart this application.
        /// </summary>
        internal static string msgClose1 {
            get {
                return ResourceManager.GetString("msgClose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the Edge browser and try again.
        /// </summary>
        internal static string msgClose2 {
            get {
                return ResourceManager.GetString("msgClose2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not delete the special &apos;_Favorites_Bar_&apos; folder
        ///Would you like to delete its contents instead?.
        /// </summary>
        internal static string msgDelBar {
            get {
                return ResourceManager.GetString("msgDelBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will also delete all of the items in the folder.
        /// </summary>
        internal static string msgDelFolder {
            get {
                return ResourceManager.GetString("msgDelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not delete the &apos;Top&apos; folder
        ///Use the &apos;Data/Clear All&apos; menu item to remove all Favorites.
        /// </summary>
        internal static string msgDelTop {
            get {
                return ResourceManager.GetString("msgDelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string msgDone {
            get {
                return ResourceManager.GetString("msgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the email: .
        /// </summary>
        internal static string msgEmailErr {
            get {
                return ResourceManager.GetString("msgEmailErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That favorite name already exists, pick another name.
        /// </summary>
        internal static string msgFavExists {
            get {
                return ResourceManager.GetString("msgFavExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string msgFileNotFound {
            get {
                return ResourceManager.GetString("msgFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That folder name already exists, pick another name.
        /// </summary>
        internal static string msgFolderExists {
            get {
                return ResourceManager.GetString("msgFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated {0}/{1} favorite icons.
        /// </summary>
        internal static string msgGenerate {
            get {
                return ResourceManager.GetString("msgGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not launch the help web page: .
        /// </summary>
        internal static string msgHelpErr {
            get {
                return ResourceManager.GetString("msgHelpErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read from the HTML file: .
        /// </summary>
        internal static string msgHTMLinErr {
            get {
                return ResourceManager.GetString("msgHTMLinErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string msgHTMLout {
            get {
                return ResourceManager.GetString("msgHTMLout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write to the HTML file: .
        /// </summary>
        internal static string msgHTMLoutErr {
            get {
                return ResourceManager.GetString("msgHTMLoutErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import from IE: .
        /// </summary>
        internal static string msgIEinErr {
            get {
                return ResourceManager.GetString("msgIEinErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string msgIEout {
            get {
                return ResourceManager.GetString("msgIEout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export to IE: .
        /// </summary>
        internal static string msgIEoutErr {
            get {
                return ResourceManager.GetString("msgIEoutErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import added {0} {1} and modified {2} {3}.
        /// </summary>
        internal static string msgImport {
            get {
                return ResourceManager.GetString("msgImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        internal static string msgLatestVer {
            get {
                return ResourceManager.GetString("msgLatestVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the Edge Favorites: .
        /// </summary>
        internal static string msgLoadErr {
            get {
                return ResourceManager.GetString("msgLoadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no changes, so there is nothing to save.
        /// </summary>
        internal static string msgNoChangeSave {
            get {
                return ResourceManager.GetString("msgNoChangeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string msgNotice {
            get {
                return ResourceManager.GetString("msgNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set Icon.
        /// </summary>
        internal static string msgNotSetIcon {
            get {
                return ResourceManager.GetString("msgNotSetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Available.
        /// </summary>
        internal static string msgNoUpdate {
            get {
                return ResourceManager.GetString("msgNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will discard any changes and reload the favorites from the Edge browser
        ///Do you want to continue?.
        /// </summary>
        internal static string msgReload {
            get {
                return ResourceManager.GetString("msgReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not rename the special &apos;_Favorites_Bar_&apos; folder.
        /// </summary>
        internal static string msgRenameBar {
            get {
                return ResourceManager.GetString("msgRenameBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That name already exists, pick another name.
        /// </summary>
        internal static string msgRenameExists {
            get {
                return ResourceManager.GetString("msgRenameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not rename the &apos;Top&apos; folder.
        /// </summary>
        internal static string msgRenameTop {
            get {
                return ResourceManager.GetString("msgRenameTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Complete.
        /// </summary>
        internal static string msgRestore {
            get {
                return ResourceManager.GetString("msgRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring the database will discard all changes made via Edge
        ///or EdgeManage since the date of the backup
        ///Do you want to continue?.
        /// </summary>
        internal static string msgRestoreDiscard {
            get {
                return ResourceManager.GetString("msgRestoreDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore the backup: {0}.
        /// </summary>
        internal static string msgRestoreErr {
            get {
                return ResourceManager.GetString("msgRestoreErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites Saved.
        /// </summary>
        internal static string msgSaved {
            get {
                return ResourceManager.GetString("msgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the Edge Favorites: .
        /// </summary>
        internal static string msgSaveErr {
            get {
                return ResourceManager.GetString("msgSaveErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been a database change in Edge, please upgrade to the latest version of EdgeManage:.
        /// </summary>
        internal static string msgSchema {
            get {
                return ResourceManager.GetString("msgSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the shortcut: .
        /// </summary>
        internal static string msgShortcutErr {
            get {
                return ResourceManager.GetString("msgShortcutErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you also like to undelete all of the items in the folder (at this level only)?.
        /// </summary>
        internal static string msgUndeleteItems {
            get {
                return ResourceManager.GetString("msgUndeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changed have been detected
        ///Do you want to save your changes to the Edge browser before exiting?.
        /// </summary>
        internal static string msgUnsaved {
            get {
                return ResourceManager.GetString("msgUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is {0} and the latest version is {1}
        ///
        ///Would you like to update now?.
        /// </summary>
        internal static string msgUpdate {
            get {
                return ResourceManager.GetString("msgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string msgUpdateAvail {
            get {
                return ResourceManager.GetString("msgUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program requires at least windows 10.0.10586 (and your system appears to be {0})
        ///Or to put it in other words, you don&apos;t need this program on your version of Windows.
        /// </summary>
        internal static string msgVersion {
            get {
                return ResourceManager.GetString("msgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not launch the home web page: .
        /// </summary>
        internal static string msgWebErr {
            get {
                return ResourceManager.GetString("msgWebErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This backup is from different version of Edge, so it may not work properly
        ///Do you wish to continue?.
        /// </summary>
        internal static string msgZipVer {
            get {
                return ResourceManager.GetString("msgZipVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        internal static string txtAddFav {
            get {
                return ResourceManager.GetString("txtAddFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string txtAddFolder {
            get {
                return ResourceManager.GetString("txtAddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Files (*.BMP;*.JPG;*.JPEG;*.GIF;*.TIF;*.TIFF;*.PNG;*.ICO)|*.BMP;*.JPG;*.JPEG;*.GIF;*.TIF;*.TIFF;*.PNG;*.ICO|All Files (*.*)|*.*.
        /// </summary>
        internal static string txtGraphicFilter {
            get {
                return ResourceManager.GetString("txtGraphicFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML files (*.htm;*.html)|*.htm;*.html|All files (*.*)|*.*.
        /// </summary>
        internal static string txtHTMLFilter {
            get {
                return ResourceManager.GetString("txtHTMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string txtRow {
            get {
                return ResourceManager.GetString("txtRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string txtRows {
            get {
                return ResourceManager.GetString("txtRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string txtTop {
            get {
                return ResourceManager.GetString("txtTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string txtXMLFilter {
            get {
                return ResourceManager.GetString("txtXMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip files (*.zip)|*.zip|All files (*.*)|*.*.
        /// </summary>
        internal static string txtZipFilter {
            get {
                return ResourceManager.GetString("txtZipFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap url {
            get {
                object obj = ResourceManager.GetObject("url", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
